version: '3.5'
services:
  test:
    image: node:alpine
    working_dir: /usr/local/src
    volumes:
      - .:/usr/local/src
      - node_modules:/usr/local/src/node_modules
volumes:
  node_modules: {  }
